### ISSUE TITLE
ActiveJob integration example

### ISSUE THREAD

**Issue by biow0lf** [hopsoft/stimulus_reflex#112]
Can anyone provide example of integration activejob in reflex flow? Something as simple as possible. e.g. re-render template in job?

**Comment by pjforde1978** [comment]
I am going to be writing some step-by-step tutorials to accomplish this, but right now I will do my very best to get you on the right track. The first thing to understand is that while it might be possible to initiate a Reflex action from the server, there are some good reasons why they should be initiated on the client - most notably callbacks. Instead, my strong recommendation is that you use the CableReady gem - upon which StimulusReflex is built - to emit an event on the client; you can pick this up and initiate a refresh by calling a Reflex on the server that doesn't do anything at all (an empty block) so that your page will be refreshed. An even simpler solution would be to just use ActionCable directly to send a message with no data that triggers a refresh, which is what I'm going to show here.

Note: I'm assuming that [you've set up your app/channels/application_cable/connection.rb](https://docs.stimulusreflex.com/authentication) such that your connections are separated; you don't want user actions bleeding to other users.

```
# app/channels/notification_channel.rb
class NotificationChannel < ApplicationCable::Channel
  def subscribed
    stream_from "notification_#{current_user.id}"
  end
end
```

```
# app/reflexes/application_reflex.rb
class ApplicationReflex < StimulusReflex::Reflex
  def refresh
  end
end
```

```
// app/javascript/controllers/notification_controller.js
import { Controller } from 'stimulus'
import StimulusReflex from 'stimulus_reflex'
import consumer from '../channels/consumer'

export default class extends Controller {
  connect () {
    this.element[this.identifier] = this
    StimulusReflex.register(this)
    if (this.element.dataset.id) {
      const controller = this
      consumer.subscriptions.create(
        { channel: 'NotificationChannel' }, {
          received () {
            controller.stimulate('ApplicationReflex#refresh')
          }
        }
      )
    }
  }
}
```

Now, to send a command to refresh the current page the user is looking at via StimulusReflex, you can use the following:

`ActionCable.server.broadcast("notification_1", "message")`

Where the 1 in this example will send the broadcast to user id 1, with two caveats: first, they won't see the message unless they have the site open at the time and second, this would presumably refresh their page regardless of what page they are currently looking at, so make sure that is desirable. For example, you can switch to resource-scoped broadcasting using the `stream_for` method instead of `stream_from`. I use this a lot for pushing updates to, for example, the show page of a resource; anyone looking at it will see the page update in realtime without refreshes necessary.

You can use the ActionCable.server.broadcast in a controller, ActiveJob, console window or even another Reflex action.

Does this make sense? Jump on our Discord server if you're still stuck and we'll do our best to help!

**Comment by leastbad** [comment]
Hi @biow0lf,

I hope that you got this sorted out. I just posted what I hope is a definitive example of this pattern on an earlier issue.

[Polymorphic comments controller example](https://github.com/hopsoft/stimulus_reflex/issues/64#issuecomment-616185117)

If this issue has been resolved, would you mind closing it?

**Comment by hopsoft** [comment]
You'd typically want to use CableReady for use-cases not directly related to a reactive UI. You can learn more about CableReady here. https://cableready.stimulusreflex.com/setup

**Comment by leastbad** [comment]
@biow0lf and anyone looking in the future: https://blog.taskbill.io/2020/06/28/cableready-is-magic/
