### ISSUE TITLE
Clearer explanation of quickstart example without javascript. 

### ISSUE THREAD

**Issue by jonathan-s** [hopsoft/stimulus_reflex#149]
## Docs

In the quickstart the first example explains how you can introduce stimulusreflex without any javascript. This seems somewhat magical, it would be nice if it was explained somewhere more clearly how the magic works behind the scenes or what assumptions are being made to make this work. 

Referring to this https://docs.stimulusreflex.com/quickstart#call-reflex-methods-on-the-server-without-any-javascript

**Comment by leastbad** [comment]
Hi @jonathan-s!

QQ: Do *you* understand how it works behind the scenes? I'm not asking as a purity test: it would genuinely help me to know where you're at with your SR journey so that I can both weight your point and consider what changes could make it more clear. No shaming here - it can be hard for me to put my brain into the perspective of a newcomer.

The issue is that you're suggesting I go into more detail on a page that is literally named "quick start". :grin:

I give an example, explain the format of a `data-reflex`, and describe how this culminates in it calling an action on the server. And to that end, the process is actually supposed to be a little magical and we think we nailed balancing magic with explanation given that *you don't need to understand anything else to use the library*.

Given that everything is covered much more extensively in the later sections, do you have any suggestions for what could be added to a **quick start** page to help lower the learning curve? Genuinely curious for suggestions.
