### ISSUE TITLE
TypeScript typing support

### ISSUE THREAD

**Issue by bbugh** [hopsoft/stimulus_reflex#152]
# Feature Request

## Is your feature request related to a problem?

Hi 👋!

Stimulus supports TypeScript, but it appears that StimulusReflex does not. Offering officially supported types would be really great.

I'm creating this issue as a conversation about how involved the library maintainers would want to be in supporting TypeScript.

## Describe the solution you'd like

Here is a summary of the options that I've seen other open source projects explore, based on the general TypeScript community's preference:

1. Library is officially written in TypeScript and the types are built in (this is what Stimulus does)
2. Officially supported types for the existing JS code are included in the package so it can "just work" for TS users
3. Official support from library maintainers in writing DefinitelyTyped community types - users can install `@types/stimulus_reflex`
4. Library maintainers are completely hands off, don't care about TypeScript at all, and it's up to the community to sort it out. 

Thoughts?

**Comment by leastbad** [comment]
Hi Brian!

TypeScript is not currently a high priority for the team working on StimulusReflex, and option 1 is not likely on any current timeline. Option 2 or 3 - I don't know much about the TS ecosystem, so these options are equally reasonable sounding - are distinctly possible if someone who is involved in our community took ownership of implementing these measures and they didn't require substantial changes to the existing codebase. I think that we can all agree that there's a happy compromise between adopting a tech and wasting energy to block it.

That brings me to your use of the interesting term "general community presence"... right now, nobody who is currently participating in the SR community - loosely defined as folks we know from hanging out on [Discord ](https://discord.gg/XveN625) - seems to be in love with TS. That's a nuanced statement, because some of us think that the type hype is a bit overblown while others thing it's fine and maybe use it, but aren't feeling as though the lack of TS support is impacting their ability to use the library. So consider this a friendly invitation to come and change our minds. 😀 

With all of that said, and having admitted that I'm not a TS expert, it's not at all clear to me how the StimulusReflex client being TS-compatible would actually be "really great". Everything happens in Stimulus controllers, and it's likely that many devs use SR without writing any JavaScript since the declarative format is quite popular. What would meaningfully change for folks calling `this.stimulate()` in their controllers if it was TS-compatible?

**Comment by bbugh** [comment]
Hi! Thank you for the thoughtful reply. I apologize for the confusion—when I said "general community preference" I meant the overall TypeScript user community. I have been part of a few TS adoptions in open source projects and have seen how this usually unfolds, and that was my attempt to offer an summary of what TS users generally request in this situation. I can see how that was not ideal framing and I've updated the request to make that clearer.

TypeScript is really great imho, so being TS compatible is also "really great" 🙂. TypeScript users would get 1) auto complete on StimulusReflex code and 2) wouldn't have to mess around with compiler flags or module declaration monkey patches to be able to use the library in their TypeScript code and 3) automatically know when refactors are required with the third party library because of API changes in the types.

Given that the surface area of the end-user API seems to be quite small, and the team's perfectly reasonable lack of interest in rewriting the library in TypeScript, 2 or 3 seems "really great" to me! 

If we move forward with StimulusReflex at our company, I'll be glad to help with this effort. Otherwise, some other TS user has the information they need now to get it going and send a PR. Thank you for taking time to engage and for this great looking library!

**Comment by leastbad** [comment]
Right on.

Well, like you said: the good news is that the public API surface area is literally one method, maybe this will be the easiest TS shim-job in history:

```js
this.stimulate('WiggleReflex#method', optional_splat)
```

Everything after the first string is zero to many optional parameters, each of any standard type eg. number, string, boolean, array, object.

**Comment by leastbad** [comment]
Moving forward, what's the best way for me to help with this issue? Is there a timeline for a conversation within your company?

If you decide not to pursue adding TS support at this time, let's close the issue. We can always reopen it later if priorities change.

**Comment by bbugh** [comment]
I think it's reasonable to close this to get it off your queue. If I or someone else comes along then it can be addressed then. Thank you for the conversation!
