### ISSUE TITLE
Possible bug when about to perform cableready operations

### ISSUE THREAD

**Issue by jonathan-s** [hopsoft/stimulus_reflex#166]
# Bug Report

## Describe the bug
In the code here: https://github.com/hopsoft/stimulus_reflex/blob/49937887c76781820f5697cee50b93adcba30c51/javascript/stimulus_reflex.js#L65

```
const urls = [
    ...new Set(data.operations.morph.map(m => m.stimulusReflex.url))
]
if (urls.length !== 1 || urls[0] !== location.href) return
```

`urls` is an array and urls[0] is a set. When compiling this javascript there is no valid comparison between the set of urls and a string. So therefore it would be better to use `!urls[0].has(location.href)`

I'm not sure why this is working as expected now to be honest.

## To Reproduce
I had a compilation step in between, not sure how rails is handling that part.

**Comment by hopsoft** [comment]
`urls[0]` should actually be a `String`. I'm not sure why the compilation step would have failed as this is valid JavaScript that runs in modern browsers.

<img width="986" alt="StimulusReflexExpo 2020-04-23 22-01-49" src="https://user-images.githubusercontent.com/32920/80174326-8e379600-85af-11ea-9027-d7617b6090e5.png">

It works because the spread operator merges the set into the array. 

<img width="285" alt="StimulusReflexExpo 2020-04-23 22-17-01" src="https://user-images.githubusercontent.com/32920/80174574-436a4e00-85b0-11ea-9c2f-a7664c935d38.png">

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by jonathan-s** [comment]
Hmm, this is what I get out of the compilation on my end. 

```
var urls = [].concat(new Set(data.operations.morph.map((function(m) {
    return m.stimulusReflex.url;
}))));
```

**Comment by hopsoft** [comment]
We probably should change from

```js
const urls = [
  ...new Set(data.operations.morph.map(m => m.stimulusReflex.url))
]
```

to

```js
const urls = Array.from(
  new Set(data.operations.morph.map(m => m.stimulusReflex.url))
)
```

**Comment by jonathan-s** [comment]
Yup, that fixes it.
