### ISSUE TITLE
Stimulus Reflex and Multi-Tenant Apps

### ISSUE THREAD

**Issue by matedemorphy** [hopsoft/stimulus_reflex#206]
Stimulus Reflex it doesn't supports multitenats apps, with Apartment gem, right?

**Comment by hopsoft** [comment]
I don't have experience using Apartment with StimulusReflex, but multi-tenancy should work just fine provided you properly scope the web socket connection to the correct user/session.

**Comment by matedemorphy** [comment]
Thanks for the answer @hopsoft, i have this until now.


connection.rb

`
def connect
  tenant = request.subdomain
  Apartment::Tenant.switch!(tenant)
  self.current_user = find_verified_user
  logger.add_tags "ActionCable", "User #{current_user.id}", "Tenant #{tenant}"
end

protected

  def find_verified_user
    if current_user = env['warden'].user
      current_user
    else
      reject_unauthorized_connection
    end
  end
`

and the error is this : `The ActionCable connection is not open! this.isActionCableConnectionOpen() must return true before calling`

**Comment by leastbad** [comment]
Hi Joseph,

Can you look at the Network Inspector, switch to the WS filter and grab a screenshot of the handshake you're seeing?

On the server side, are you seeing messages from ActionCable in your stdout stream?

Could you verify that if you create a standard ActionCable channel that you're able to connect and send a simple message down the wire?

`rails generate channel test`
`stream_from "test"` in your app/channels/test_channel.rb 
`received(data) { console.log(data) }` in your app/javascript/channels/test_channel.js
`ActionCable.server.broadcast("test", "ActionCable rocks")` in your Rails console CLI

If basic raw ActionCable isn't working, we can try to help troubleshoot but the issue is Apartment + ActionCable, not StimulusReflex.

**Comment by matedemorphy** [comment]
@leastbad  indeed, returns nil. Thanks, although my suffering continues, i will try in Apartment Issues.

**Comment by leastbad** [comment]
Please keep us posted. I'll circle back in a few days.

**Comment by leastbad** [comment]
@matedemorphy I wrote a quick and simple test to verify that ActionCable is working. As it happens, I'm not 100% sold on the code I gave you earlier. Thanks for inspiring me to be more thorough.

https://docs.stimulusreflex.com/troubleshooting#verify-actioncable

Can you please try this out and let me know if you have any feedback?

**Comment by matedemorphy** [comment]
@leastbad confirmed, there are no incompatibilities between Stimulus Reflex and ActionCable. In fact, i just fork https://github.com/hopsoft/stimulus_reflex_expo repository and everything works fine.

**Comment by matedemorphy** [comment]
@leastbad confirmed, there are no conflicts between Stimulus Reflex and ActionCable. In fact, i just fork https://github.com/hopsoft/stimulus_reflex_expo repository and everything works fine.

**Comment by leastbad** [comment]
Hey @matedemorphy, I sure hope that the expo site works! But that's not really answering my question. Can you please confirm, ideally using the code I provided for you in the docs above, that ActionCable is working in the application that has Apartment running in it?

Sorry to sound hung up on this but the error message you reported is **strongly** correllated to ActionCable not connecting in your environment. It's frustrating to troubleshoot when it comes out late in the process that things "aren't plugged in".

**Comment by matedemorphy** [comment]
@leastbad no, is not, sadly, thats why i'm can confirm that the problem is with the Apartment gem.

**Comment by leastbad** [comment]
Do you have `<%= action_cable_meta_tag %>` in your application.html.erb?

**Comment by leastbad** [comment]
Also, do you have `user101.lvh.me` in your `config.hosts` array in config/environments/development.rb?

**Comment by leastbad** [comment]
You might also find some insight in https://stackoverflow.com/a/40288799

Please let me know what ends up working for you.

**Comment by matedemorphy** [comment]
@leastbad i have those configurations. Perhaps the problem is because i'm running the app in a Vagrant Box.

**Comment by leastbad** [comment]
Yet the Expo project works fine... so I don't think that's it.

When you go to http://user101.lvh.me:3000/cable what do you see?

**Comment by matedemorphy** [comment]
@leastbad  `Page not found`, i don't think there is a solution for this in Rails 6 yet.

**Comment by leastbad** [comment]
This 100% sounds like you have a problem with Vagrant not mapping your websockets properly.

Honestly, Vagrant sucks. Can you just install rvm and run this on your actual computer? It'll be 4-5x faster and it will actually work?

**Comment by matedemorphy** [comment]
@leastbad agree, but i'm on a windows machine.

**Comment by leastbad** [comment]
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by matedemorphy** [comment]
but a simple  `puts` should works in a Reflex even if there is some outer problem with ActionCable right?

**Comment by matedemorphy** [comment]
in view:

`a data-reflex="click->DemoReflex#test" href="#" = Test`

in Reflex:
`
class DemoReflex < ApplicationReflex
  def test
    puts "it works!"
  end
end
`
It will not recall the Rails Controller because of the ActionCable problem, but stil should print "it works!" in the console?

**Comment by leastbad** [comment]
Joseph, can you explain how that reflex action could fire if ActionCable isn't working?

Bone conduction? Telepathy?

**Comment by matedemorphy** [comment]
Calm down, with my question you can see how stuck I am.

**Comment by leastbad** [comment]
I'm sorry for losing patience. I want very badly for your problem to be solved.

It is hard when people say things that make you wonder if they have followed (or understood) earlier instructions. I am, after all, taking time from my work to help with yours. I'm happy to do this but it is scary to be confronted with questions or comments that you can't know how to begin solving because they don't make sense. In your case, you sound like and present as a capable developer, and you say that you tested AC but your environment is not working. I made several suggestions and it all feels like we're at an impasse: tell me what to change but don't make me change anything.

So no, it's not going to do anything until you get ActionCable working. If ActionCable is working, that means you ignored my request to test via the code I wrote for you, and told me that you did it anyhow. Hopefully you can see why this might leave me feeling frustrated.

**Comment by leastbad** [comment]
Also, for the future: telling someone to "calm down" is pretty much guaranteed to make them feel really uncharitable emotions towards you. It basically means the opposite.

**Comment by hopsoft** [comment]
I understand that things can be frustrating when they aren't working _(especially given all the various development/deployment configurations we can find ourselves using)_, but @leastbad, I'm  obligated to point out that this exchange is straying from our [Code of Conduct](https://github.com/hopsoft/stimulus_reflex/blob/master/CODE_OF_CONDUCT.md) and is not acceptable. Please take a moment to reread. Sometimes it's best to step away and say nothing when we're feeling exasperated. 

---

@matedemorphy We need you to verify that the ActionCable web socket is connected and working before we can begin troubleshooting StimulusReflex issues. StimulusReflex is built on top of ActionCable which means if the underlying transport mechanism isn't working, StimulusReflex will not work. The answer to your last question, **"Should it print 'it works' in the console?"** is: _yes if the ActionCable web socket is connected and working_. 

Unfortunately it sounds like the ActionCable web socket is not yet working for you. My guess is that this is due to your port forwarding configuration for Vagrant + Virtual Box. I'm not a Vagrant user any more, so troubleshooting this is challenging. I did find a few suggestions on this Reddit thread that may prove helpful. https://www.reddit.com/r/rails/comments/5751l6/action_cable_and_vagrant/

**Comment by matedemorphy** [comment]
@hopsoft @leastbad  since i am using the aparment gem, i have to use subdomains, lvh.me in development environment, it could related to that?

**Comment by majksner** [comment]
@matedemorphy This is how my `connection.rb` and one channel looks like:

```ruby
# frozen_string_literal: true

# app/channels/application_cable/connection.rb
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user, :tenant

    def connect
     # Apartment::Tenant.current doesn't work here so the only way I could think of is to use the subdomain to get tenant
     # This is only if you use Apartment::Elevators::FirstSubdomain
      tenant = request.subdomain.empty? ? request.host.match(/(www\.)?(?<sld>[^.]*)/)['sld'] : request.subdomains(0).first
      Apartment::Tenant.switch!(tenant)
      self.tenant = tenant
      self.current_user = find_verified_user
      reject_unauthorized_connection unless current_user
    end

    private

    def find_verified_user
      @user ||= env['warden'].user
    end
  end
end

```

And here is the example of the channel

```ruby
class TestChannel < ApplicationCable::Channel
  def subscribed
    reject unless current_user
    stream_from("#{tenant}_test_#{current_user.id}")
  end

  def unsubscribed
    stop_all_streams
  end
end
```

Triggering broadcast:

```ruby
ActionCable.server.broadcast("#{Apartment::Tenant.current}_test#{user.id}", {data: 'your data'})
```
