### ISSUE TITLE
Documentation Request for a Rails 6.x app with 5.2 defaults

### ISSUE THREAD

**Issue by brandondrew** [hopsoft/stimulus_reflex#265]
# Documentation Request

Stimulus Reflex looks awesome and the documentation appears to have been crafted with great care and loving attention to detail!  

However, my particular use case has not been mentioned, and it's unclear to me if one that has been mentioned is directly applicable.  I have a Rails 6 app that still has Rails 5.2 defaults (`config.load_defaults 5.2`).

It would be really helpful if you could clarify whether the [Rails 5.2+ Support section](https://docs.stimulusreflex.com/setup#rails-5-2-support) is _directly_ applicable, or whether I would have to modify the directions there in some way. 

https://github.com/hopsoft/stimulus_reflex/blob/master/docs/setup.md

The features I'm working on in my app were just reprioritized, so I'm no longer in a position (at the moment) to take time to verify my hunch that the real question is simply: _are you using webpacker or sprockets?,_ and the version of Rails is immaterial.  But it would be nice if this was specifically mentioned in the README, to make things clear for this situation.

Thanks!

**Comment by leastbad** [comment]
Hi Brandon!

Everything that you're saying makes sense on a high level. I should be clear that I really wasn't doing much development during the v4-5.x time period, so I'm really only familiar with `load_defaults` in the same way that I've never seen "The Godfather" but I feel like I could describe it to you.

Realistically, while I genuinely love that writing documentation forces me to get more familiar with corners of Rails I wouldn't otherwise get the opportunity to work with, realistically I am not gunning for certification-level intuition about every detail. That means that you're actually far closer to being the person to drive this part of the documentation than I am. (I certainly don't feel like I'm holding anything back, so if stuff is missing...)

What I can say is that it would be great to have a dialogue in this issue where you make suggestions and I transmute them into the documentation. I am not realistically going to have time to set up a Rails 6 app that is running with 5.2 load defaults and figure out all of the subtleties. I am, at the end of the day, a volunteer... but the bigger issue is that there's honestly just too many priorities (even for documentation!) waiting for my attention in this project, and I don't want to build any false hope.

If you or someone else that comes along is able to give me a solid list of changes, I will definitely treat them with respect.

**Comment by brandondrew** [comment]
Okay, I understand a little better now.  I (wrongly) assumed that it was simply a matter of not thinking to mention that situation, rather than not actually knowing precisely how it would work.  I expect to come back to this in the future, so I'll try to contribute my experiences to clarifying this.

**Comment by leastbad** [comment]
Hey @brandondrew I just wanted to follow-up and ask if you'd unblocked yourself? Happy to work your experiences into the documentation.
