### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by dixpac** [hopsoft/stimulus_reflex#289]
👋 

Playing with stimulus_reflex on our production app, and there is an issue I've encountered.

Our app is classic SAAS app. We store different accounts in the same database. We don't scope per subdomain, but we scope with url, for example : `app.demo/{:account_slug}/`.

Account extraction happens inside the `AccountSlug` middleware which looks like this:

```ruby
module AccountSlug
  PATTERN = /(\d{1,})/
  FORMAT = '%07d'

  def self.decode(slug) slug.to_i end
  def self.encode(id) FORMAT % id end

  # We're using account id prefixes in the URL path. Rather than namespace
  # all our routes, we're "mounting" the Rails app at this URL prefix.
  #
  # The Extractor middleware yanks the prefix off PATH_INFO, moves it to
  # SCRIPT_NAME, and drops the account id in env['docsnote.account.id'].
  #
  # Rails routes on PATH_INFO and builds URLs that respect SCRIPT_NAME,
  # so the main app is none the wiser. We look up the current account using
  # env['docsnote.account.id'] instead of request.subdomains.first
  class Extractor
    PATH_INFO_MATCH = /\A(\/#{AccountSlug::PATTERN})/

    def initialize(app)
      @app = app
    end

    def call(env)
      request = ActionDispatch::Request.new(env)

      # $1, $2, $' == script_name, slug, path_info
      if request.path_info =~ PATH_INFO_MATCH
        request.script_name   = $1
        request.path_info     = $'.empty? ? '/' : $'

        # Stash the account's ID.
        env['docsnote.account.id'] = AccountSlug.decode($2)
      end

      @app.call env
    end
  end
end
```

```ruby
# frozen_string_literal: true

module SetAccount
  extend ActiveSupport::Concern
  included do
    before_action do
      Current.account = Account.find request.env["docsnote.account.id"] if request.env["docsnote.account.id"]
    end
  end
end
```

```ruby
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SetAccount
  ...
end
```

---------------------------------------------------------------------------------

Inside the reflex everything works fine, except page morphing, when you try to re-render current page [this line](https://github.com/hopsoft/stimulus_reflex/blob/master/lib/stimulus_reflex/reflex.rb#L83) throws an error
<img width="1280" alt="Screenshot 2020-08-12 at 16 43 06" src="https://user-images.githubusercontent.com/7427365/90029232-ec9d9700-dcba-11ea-8882-7e1ad3ec31ae.png">

<img width="1067" alt="Screenshot 2020-08-12 at 16 49 32" src="https://user-images.githubusercontent.com/7427365/90030026-d93efb80-dcbb-11ea-85b2-8d70cd33ee93.png">

(Which is understandable since `localhost:3000/1/` doesn't exist it needs `AccountSlug` middleware to work properly )

**Comment by leastbad** [comment]
Ugh! I'm sorry you're dealing with this. It doesn't have a quick solution, as you're likely already aware, if you want to keep using page morphs.

Usually when URL changing comes up, it's because people fundamentally don't understand what SR is for and/or trying to do. That's clearly not what this is about.

Your best course of action here - if it hopefully works for you - is probably to use `morph "body", ApplicationController.render()` but it's not ideal because you won't have access to your controller actions.

It's (far) beyond the scope of SR to re-implement Rack but I wonder if we could look into providing an initializer that accepts a lambda; you could do a Regex replacement, perhaps?

**Comment by leastbad** [comment]
Hi Dino, I wanted to check in and see if you figured this out.

Since we last discussed the issue, we've been able to add support for the `acts_as_tenant` gem: https://docs.stimulusreflex.com/authentication#multi-tenant-applications

When I look at the implementation I did for the tenant demo (`tenant` branch of `https://github.com/leastbad/stimulus_reflex_harness/tree/tenant`) it seems remarkably similar to your Current.account implementation. Of course, you'll still have to adapt it but check out https://github.com/leastbad/stimulus_reflex_harness/blob/tenant/app/channels/application_cable/connection.rb and tell me what you think.

**Comment by dixpac** [comment]
@leastbad I'm so sorry for not getting back to you. Didn't have time to investigate this further, but I will! I will check your links and get back if I have anything  add.

One more time sorry :)

**Comment by leastbad** [comment]
Happy to reopen if you ever want to revisit, @dixpac!

**Comment by excid3** [comment]
Ran into this with Jumpstart Pro as well. I was testing previously without the middleware, but since StimulusReflex isn't aware of the middleware, it won't set the `SCRIPT_NAME` properly when processing requests. 

In Rails, the middleware rewrites `localhost:3000/1/projects` to `localhost:3000/projects` with `request.script_name = "/1"` This way Rails never sees the `/1`.

StimulusReflex doesn't run the middleware, so it tries to look up `localhost:3000/1/projects` which is not a route in Rails.

A potential solution is mounting ActionCable at `/1/cable` so that we could store the script name and pass it along during SR requests. Rails does seem to store the original request for the websocket which we can probably access the script_name from. https://github.com/rails/rails/blob/6-1-stable/actioncable/lib/action_cable/connection/base.rb#L150-L156

I noticed SR is forcing `Rack::SCRIPT_NAME => "",` so I think that would be the only piece we'd need to change if we can access the original script_name for the ActionCable request.

Trying to see if I can get that to work.

**Comment by excid3** [comment]
Related: https://github.com/rails/rails/issues/34023

**Comment by leastbad** [comment]
@excid3 just so I'm on the same page, is the 1 in this the `id` of the Project or is this something to do with how `acts_as_tenant` works? I don't understand how `localhost:3000/projects/1` becomes `localhost:3000/1/projects`

**Comment by excid3** [comment]
It's the tenant id. So `/1/projects/2` would be tenant #1, project #2 for example. 

Rails never sees the /1 as it's stripped using script_name in the middleware.

In theory, that should be accessible in the actioncable connection if we mounted at /1/cable

**Comment by leastbad** [comment]
It's not promising when an issue opened by a Basecamp employee hasn't been closed in two years. That does sound like the exact same issue.

So, `config.action_cable.mount_path` gets set in the environment. How would you overwrite it on a per-tenant basis? Something tells me that you can't just pass in a proc.

**Comment by excid3** [comment]
ActionCable isn't an isolated namespace so I don't think it applies.

**Comment by excid3** [comment]
And you just set the meta tag to change the actioncable url.

**Comment by leastbad** [comment]
Duh, right - of course. The mount path is just getting printed into the view.

Well, you might want to obfuscate the tenant id but it sounds like a viable solution.

**Comment by excid3** [comment]
Not real sure why script name is empty inside the actioncable connection. It should pass through the middleware same as the other requests.

**Comment by leastbad** [comment]
It might be worth pinging @georgeclaghorn oh wait I just did

**Comment by excid3** [comment]
@leastbad would you reopen this?
