### ISSUE TITLE
Fail loudly if there's a version mismatch between the gem and the npm package.

### ISSUE THREAD

**Issue by noise-machines** [hopsoft/stimulus_reflex#294]
# Feature Request

Hi folks! Thanks for the great work you've done on Stimulus Reflex, and for the friendly and welcoming support I received in the Discord server.  

## Is your feature request related to a problem?

I recently got bitten by having a mismatched version of the gem (3.2.3) and the npm package (3.3.0.pre2).

## Describe the solution you'd like

I know you mention that mismatch in your very handy troubleshooting guide, but it'd be even more helpful if Stimulus Reflex checked for this scenario and complained loudly about it.

I thought I had confirmed they were at the same version, but I was mistaken. If SR complained loudly in this scenario, it would've saved me some time and helped me avoid some very strange error messages.

**Comment by leastbad** [comment]
I'm sure that we'd be happy to implement this functionality if there's a reasonably approachable way to do it.

Could you do some research on how other projects with Ruby+JS components handle this and report back?

**Comment by RolandStuder** [comment]
The PR #297 (so far) addresses half the issue. Running `rails stimulus_reflex:install` will currently install mismatched versions as `yarn` command used in that task will always install the latest version.

But mismatches between gem and npm package can come up, when you `bundle update` or `yarn upgrade` or otherwise adjust one of the versions.

I suggest we do a separate PR to address this.

---

I am not in love of doing a check in every reflex call or cable connection. I would prefer doing the checks in some form during the initialization of the rails app and then be more or less aggressive about informing the user.

Suggestion:

* use some form of initialization of SR to do the check.
* either raise an error (and provide a config option, to opt out of these errors?)
* or warn client and/or server side about the mismatch (using some class variable to store the result of the check).

My questions:

* Do you agree that the check should happen when initializing the app? Or would a memoized check on a reflex trigger be find as well?
* If you prefer check on initialization, would you raise and error and warn then, or upon execution of reflexes?
* If we warn when executing reflexes would you do it client or server side (I think client side, as this is usually where one is looking when troubleshooting)

references on how others do checks:

* `spring` does a check on `run`: https://github.com/rails/spring/blob/309ec0defa2b5c48d51cdb7d19251f6027a1b31b/lib/spring/client/run.rb#L116
* an example how to initialize stuff in engines: see refinery_crm https://github.com/refinery/refinerycms/blob/e49a6bebefe34bedcca932887f1446f084a23c33/core/lib/refinery/core/engine.rb#L43 (not sure if this is something custom or a default mechanism)

btw: Once established, we could then use the very same mechanism to check if the cache is enabled #258

**Comment by leastbad** [comment]
I am also not into giving an alert on every Reflex. I suggested on #297 that you put an obnoxious, impossible to ignore message in `lib/stimulus_reflex.rb` right after all of the requires. This would emit the warning when the Rails server starts.

**Comment by ParamagicDev** [comment]
Perhaps StimulusReflex could generate an initializer file and the initializer file could check both the package version and gem version. On top of it, perhaps SR could have a configuration option to disable version checking in the initializer.

On top of it, you could also control what you would like to do on a version mismatch IE: "warning", "error", "info"

**Comment by leastbad** [comment]
Do we want to even bother emitting a client error? My inclination was to drop a big ol ASCII FU into the server console log.

Pardon me if I misunderstood: I think of those as client log levels.

**Comment by piotrwodz** [comment]
@ParamagicDev 

> On top of it, perhaps SR could have a configuration option to disable version checking in the initializer.

When would you benefit from disabling?

@RolandStuder @leastbad Outputting a warning into the console is exactly what I would expect here. The warning log with some help guidance.

**Comment by ParamagicDev** [comment]
@piotrwodz maybe my idea is a little too aggressive, but I would like to see the whole process error out on a version mismatch and then allow users to disable the check in case they're doing like a `yarn link` and have a reason to disable it.

However, if the plan is just to make it obvious in the console, the disabling of the warning doesn't make sense.

**Comment by RolandStuder** [comment]
@ParamagicDev On second thought  I actually would appreciate if the process just errors out, then you really know something is up. Usually when firing up a rails server, I will not really pay attention to the log output.

@hopsoft What do you think? Just a loud warning or raising an error and halting the startup of the application?

**Comment by RolandStuder** [comment]
Instead of warning on startup, it would also be possible to warn or prompt to update after the install. Using a `after_install` hook bundler provides. 

https://github.com/rubygems/bundler/blob/master/lib/bundler/plugin/events.rb
