### ISSUE TITLE
reflexData missing on element in beforeReflex

### ISSUE THREAD

**Issue by LukeClancy** [hopsoft/stimulus_reflex#443]
# Bug Report

## Describe the bug

`element.reflexData` in JS beforeReflex callback seems to be missing in 3.4.1 and later. Temporary fix is to go back to 3.4.0. Here is the code that I noticed the problem on:

```js
// arena controller
beforeReflex( element, reflex, e_o, reflexId ) {
    super.beforeReflex( element, reflex, e_o, reflexId )
    element.reflexData[reflexId].attrs["data-arena-id"] = this.arenaTarget.getAttribute("data-arena-id")
    element.reflexData[reflexId].attrs["data-competition-id"] = this.arenaTarget.getAttribute("data-competition-id")
  }
```
```js
// application controller
  beforeReflex (element, reflex, e_o, reflexId) {
    element.reflexData[reflexId].attrs["data-tab-id"] = this.application.get_tab_id()      // <-- error thrown, element.reflexData is undefined
    q("#notice_area").innerHtml = ""
  }
```
Note that it is still an issue in the `arena` controller if the `super` method is removed. Thanks for the help

## To Reproduce

Create a beforeReflex and attempt to get reflexData from the element

## Expected behavior

Expected behavior is to either
1. For `reflexData` to be there or
2. For there to be a recent alternate path to providing data backend in the element that I did not know about, and that `reflexData` was depreciated

## Sample Error
```
Uncaught TypeError: element.reflexData is undefined
    beforeReflex application_controller.js:48
    beforeReflex arena_controller.js:15
    invokeLifecycleMethod lifecycle.js:34
    js lifecycle.js:46
    dispatchLifecycleEvent lifecycle.js:115
    stimulate stimulus_reflex.js:220
    __perform stimulus_reflex.js:260
    node_modules application-ae311dde77d3b7c0921e.js:6535
    node_modules application-ae311dde77d3b7c0921e.js:6508
```
## Versions

x >= 3.4.1

### StimulusReflex

- Gem: 3.4.1
- Node package: 3.4.1

### External tools

- Ruby: 2.7.1
- Rails: 6.0.3
- Node: 12.18.2

### Browser

- Firefox for Ubuntu v84.0.2 64bit

**Comment by leastbad** [comment]
Yikes, I really thought we'd worked out all of the kinks with this functionality.

I'm sorry that you're having trouble here and I'm glad that v3.4.0 provides a workaround. I will be digging in on this shortly.

**Comment by leastbad** [comment]
Hey Luke,

I have a working theory about the change you're seeing which I'd like you to investigate before I go searching for glasses that are on my face!

First, please give this a [re-]read: https://docs.stimulusreflex.com/rtfm/reflexes#understanding-stimulusreflex-controllers

v3.4.1 fixed a major problem that had been present in previous versions, which is that if the meta-data associated with a Reflex was attached to the element that initiated the Reflex instead of the element holding the controller, SR would not be able to locate a controller upon which to emit events from after the Reflex was completed. The correct solution is to make sure that the meta-data is always attached to the item holding the controller responsible for the Reflex.

Now, lots of times the element which initiated the Reflex and the element the controller is on are in fact the same element. This is fine, unless you plan to remove the element as part of the Reflex operation. You can see how the two are indeed discussed as being different in https://docs.stimulusreflex.com/rtfm/lifecycle#conventions

My suspicion is that you're looking for the metadata on the reflexElement instead of the controller element. If they are the same element, then you'll be able to access the reflexData through `element.reflexData[reflexId]`. However, if they are indeed on different elements, you're probably looking for `this.element.reflexData[reflexId]` as the more reliable default, as it will work in both scenarios.

Please let me know if this helps, or if there's still evidence of a problem we haven't anticipated.

**Comment by LukeClancy** [comment]
Hey Leastbad

That solved it! From my understanding, it looks like reflexData was moved as it could not be reliably connected to the element that started the reflex. From 3.4.0 to 3.4.1, in callbacks, reflexData moved from "element" to to "this.element". This also makes sense as reflexData is a list of many reflexes. So from a object-oriented perspective it should be with the parent data-controller element and not the child triggering element.

Thanks for your help! I am enjoying the library! I did a SR infinite scroll a while back which was awesome

**Comment by leastbad** [comment]
I'm thrilled that you got sorted. And yeah, CableReady in particular is amazing for infinite UIs.

It's always tricky when the correct answer is to do what should have been done all along. After all, why would the button you clicked on be so important, right? It's very common for SR devs to put the SR controller on a container element that contains multiple rows of data. That way, if those rows contain a "delete" button, you can kill the data row without blowing away the SR controller that you're counting on to raise life-cycle events.

It all makes sense once you spend some time with it. For me, documenting the library is the ultimate learning hack.
